GL_EXT_null_initializer
KhronosGroup/GLSL pull request #151
Opened 2021-01-25 16:16 UTC by alan-baker

* Adds a null initializer syntax (empty braces) that can be used to
  initialize variables
* Allows shared variables to use null initializers

2021-02-20 20:22 UTC, seanbaxter commented
How does this operate with Aliased smem, where you have multiple Workgroup declarations for the same memory? Would you put the zero initializer on just one of them?

2021-02-22 18:15 UTC, alan-baker commented
Yes, you only need the initializer on one of the variables. There are (or will be) CTS tests for that interaction.

2021-03-04 14:56 UTC, gnl21 commented on extensions/ext/GL_EXT_null_initializer.txt
> +   initializers may only be used to initialize sized-types.
I'm not sure what "sized types" here means. (Also, I'm not sure it should be hyphenated). Are you disallowing opaque types (that don't have a fixed size in memory) or unsized arrays? Or both?

The spec also tries to say when errors will occur if the rules are not followed, ie. whether it's a compile- or link-time error.

```suggestion
   It is a compile-time error to null initialize any other type, or to null initialize an
   unsized array type.
   
   Null initialization can be achieved by using an empty brace expression.
```

2022-09-27 13:19 UTC, dgkoch commented
@alan-baker can you please address feedback so this can be merged?

2022-10-25 16:55 UTC, dgkoch requested changes

2022-10-25 16:55 UTC, dgkoch commented on extensions/ext/GL_EXT_null_initializer.txt
> +  Draft
```suggestion
  Complete
```

2022-10-25 16:55 UTC, dgkoch commented on extensions/ext/GL_EXT_null_initializer.txt
> +  TBD
You can probably just drop this section since we don't assign numbers to GLSL-only extensions.

2022-10-25 16:55 UTC, dgkoch commented on extensions/ext/GL_EXT_null_initializer.txt
> +  This extension adds a null initializer to GLSL and allow shared variables in
```suggestion
  This extension adds a null initializer to GLSL and allows shared variables in
```

2022-10-25 16:55 UTC, dgkoch commented on extensions/ext/GL_EXT_null_initializer.txt
> +  compute shaders to be null initiailzed. Null initializers are specified using
```suggestion
  compute shaders to be null initialized. Null initializers are specified using
```

2022-10-25 16:55 UTC, dgkoch commented on extensions/ext/GL_EXT_null_initializer.txt
> +    #extension GL_EXT_null_initialize_shared_memory : <behavior>
```suggestion
    #extension GL_EXT_null_initializer : <behavior>
```

2022-10-25 16:55 UTC, dgkoch commented on extensions/ext/GL_EXT_null_initializer.txt
> +    #define GL_EXT_null_initialize_shared_memory    1
```suggestion
    #define GL_EXT_null_initializer    1
```

2022-10-25 16:55 UTC, dgkoch commented on extensions/ext/GL_EXT_null_initializer.txt
> +    Variables declared as shared may only have null initializers (see section 4.3.8.1).
```suggestion
    Variables declared as shared may only have null initializers (see section 4.1.11.1).
```
?

2022-10-25 17:57 UTC, dgkoch approved these changes
LGTM now

2023-06-07 16:10 UTC, merged